uggh; too many kinks in tree

diff --git a/gaf b/gaf
--- a/gaf
+++ b/gaf
@@ -214,7 +214,7 @@ gaf_cycle() {
         do
             echo -n $f...
             $0 save $f
-            $0 merge $remote/$f  >&/dev/null || die "branch '$f' has conflicts or upstream has not been defined"
+            $0 rebase $remote/$f  >&/dev/null || die "rebase '$f' on "$remote" failed"
             $0 restore $f
         done
         echo
